headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Standard
options:
  alignment:
    options:
      - left
      - right
      - center
  fontSize:
    options:
      - tiny
      - small
      - big
      - huge
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - underline
  - strikethrough
  - '|'
  - alignment
  - fontSize
  - fontFamily
  - fontColor
  - fontBackgroundColor
  - '|'
  - bulletedList
  - numberedList
  - '|'
  - insertImage
  - mediaEmbed
  - '|'
  - link
