field: 404dca4f-574e-4efc-ac08-72a4734ad700 # Page Builder
fieldLayouts:
  0cd52bfa-483c-4ad9-bf73-305b123ba4bd:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 4b7d2b5f-cb80-442f-9c5d-7a666ed3d078 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3aecf5d2-1394-418a-a209-b54d567fcbcf
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 8b383f81-19ad-4ada-a52c-77b7ad98c94d # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 341bbfc1-c21c-4cf7-ad0d-07c819650f6f
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 373700c2-7a6a-4acc-afce-6c166f4fbd25
        userCondition: null
fields:
  4b7d2b5f-cb80-442f-9c5d-7a666ed3d078: # Text
    columnSuffix: nakfhdyi
    contentColumnType: text
    fieldGroup: null
    handle: text
    instructions: null
    name: Text
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: 04da89f2-3a77-428d-901f-3c35f0ccb546 # Standard
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  8b383f81-19ad-4ada-a52c-77b7ad98c94d: # Image
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: null
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: true
      allowUploads: true
      allowedKinds:
        - image
        - video
      branchLimit: null
      defaultUploadLocationSource: 'volume:3dc47c12-857f-4548-82de-3d0e23beda37' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maintainHierarchy: false
      maxRelations: 1
      minRelations: null
      previewMode: full
      restrictFiles: true
      restrictLocation: true
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:3dc47c12-857f-4548-82de-3d0e23beda37' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      sources: '*'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: columnTextImage5050
name: 'Column Text Image 5050'
sortOrder: 5
