field: 404dca4f-574e-4efc-ac08-72a4734ad700 # Page Builder
fieldLayouts:
  7f5f9eb1-c731-45d3-aecc-4b3068eae2c4:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: abc75faf-39e1-462a-b6ba-4d82318ba95e # Text 1
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f133f6c4-da98-4cdf-8280-ce189bb8bc16
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: da12ce31-1a6f-4d37-b4aa-8c9cd56f7b26 # Text 2
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e6d01f06-23fd-47a6-94ae-ea8f65f9454d
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 77cc2243-a112-497a-b41a-98c4e776fabf
        userCondition: null
fields:
  abc75faf-39e1-462a-b6ba-4d82318ba95e: # Text 1
    columnSuffix: elbtklze
    contentColumnType: text
    fieldGroup: null
    handle: text1
    instructions: null
    name: 'Text 1'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: 04da89f2-3a77-428d-901f-3c35f0ccb546 # Standard
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: true
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
  da12ce31-1a6f-4d37-b4aa-8c9cd56f7b26: # Text 2
    columnSuffix: twbdlivp
    contentColumnType: text
    fieldGroup: null
    handle: text2
    instructions: null
    name: 'Text 2'
    searchable: false
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      ckeConfig: 760153a3-3abd-4900-8448-46ea71a12960 # Simple
      columnType: text
      defaultTransform: null
      enableSourceEditingForNonAdmins: false
      purifierConfig: null
      purifyHtml: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      showWordCount: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\ckeditor\Field
handle: columnText5050
name: 'Column Text 5050'
sortOrder: 2
